### ISSUE TITLE
Wrong data being displayed inside the job configuration card

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/job-manager#703] opened 2024-04-26 04:39 UTC
## Current behavior

If a job is missing draft data and the job is not in pending state, then on clicking the job we try to get the job information on the basis of jobId and if that jobId has some record in any other state then also that data gets displayed irrespective of its state.

## Expected behavior

On clicking a job, only either draft or pending data for a job needs to be displayed.

## Steps to reproduce the issue

1. Find a job in oms(that is available in job manager app) that does not have any data in draft or pending state, but has some data in any other state.
2. Now click on the job in the app and verify that the data gets displayed of a state other than draft and pending.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

This is a specific case when data is not correct where systemJobEnumId matches the jobId for a completed or failed job.

**Comment by Dhiraj1405** [comment] 2024-07-31 13:10
Closing as not able to reproduce.

**Closed by Dhiraj1405** 2024-07-31 13:10 UTC
Labels: bug
